kind: pipeline
type: kubernetes
name: default

steps:
  - name: test
    image: maven:3.6.3-jdk-8
    commands:
      - mvn test
  - name: build
    image: maven:3.6.3-jdk-8
    commands:
      - mvn install -DskipTests=true
  - name: deploy
    image: caprover/cli-caprover:latest
    commands:
      - git checkout -b release-${DRONE_TAG}
      - npx caprover deploy -h $CAPROVER_DOMAIN -p $CAPROVER_PASSWORD -b release-${DRONE_TAG} -a $CAPROVER_APPNAME
    environment:
      CAPROVER_DOMAIN:
        from_secret: CAPROVER_DOMAIN
      CAPROVER_APPNAME:
        from_secret: CAPROVER_APPNAME
      CAPROVER_PASSWORD:
        from_secret: CAPROVER_PASSWORD
    depends_on: [build, test]
    when:
      event: tag
