kind: pipeline
type: kubernetes
name: default

steps:
  - name: code-analysis
    image: maven:3.6.3-jdk-8
    commands:
      - mvn verify sonar:sonar -Dsonar.host.url=$SONAR_HOST -DskipTests=true
    environment:
      SONAR_HOST:
        from_secret: SONAR_HOST
  - name: test
    image: maven:3.6.3-jdk-8
    commands:
      - mvn test
  - name: build
    image: maven:3.6.3-jdk-8
    commands:
      - mvn clean install -DskipTests=true
    depends_on: [test, code-analysis]
 - name: deploy
    image: node:lts
    commands:
      - sudo npm install -g caprover
      - caprover deploy -h $CAPROVER_DOMAIN -p $CAPROVER_PASSWORD -b master -a $CAPROVER_APPNAME
    depends_on: [build]
