kind: pipeline
type: kubernetes
name: default

steps:
  - name: test
    image: maven:3.6.3-jdk-8
    commands:
      - mvn test
  - name: build
    image: maven:3.6.3-jdk-8
    commands:
      - mvn clean install -DskipTests=true
  - name: deploy
    image: node:lts
    commands:
      - npx caprover deploy -h $CAPROVER_DOMAIN -p $CAPROVER_PASSWORD -b master -a $CAPROVER_APPNAME
    depends_on: [build, test]
